### ISSUE TITLE
[Bug]: An Example Bug

### ISSUE THREAD

**Issue by 5ila5** [5ila5/template_test#1]
### I Have A Problem With:

A specific source, Sensor configuration

### What's Your Problem

My Source does not return the right data and my sensor does not makes the right thing.

Really think this is a bug

### Source (if relevant)

broxtowe_gov_uk

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 01:54:04 (1 occurrences)
Last logged: 01:54:04

fetch failed for source Stoke-on-Trent: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/stoke_gov_uk.py", line 49, in fetch date = datetime.strptime(date_time, DATE_FORMAT).date() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime tt, fraction, gmtoff_fraction = _strptime(data_string, format) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime raise ValueError("time data %r does not match format %r" % ValueError: time data '13/10/2023' does not match format '%d/%m/%Y %H:%M:%S'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: broxtowe_gov_uk
      args:
        uprn: 100031343805
        postcode: NG9 2NL

sensor:
  - platform: waste_collection_schedule
    name: recycling
    value_template: '{{value.daysTo}}'
    types:
      - Empty Bin REC 240 STD
  - platform: waste_collection_schedule
    name: gardenwaste
    value_template: '{{value.daysTo}}'
    types:
      - EMPTY BINS ORG 240 STD
  - platform: waste_collection_schedule
    name: general
    value_template: '{{value.daysTo}}'
    types:
      - EMPTY BINS RESIDUAL BIN
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
